### PR TITLE
Fix sum function answer

### PR DESCRIPTION
**Pull request by bbuck**
The current sum function answer will only catch some precision errors while adding. This fix will catch any precision errors now.

### CODE REVIEW

**Comment by nathansmith** [comment]
Ah, good call. But, rather than multiply the total, and immediately divide it again, I'm multiplying each value as it comes in. So, I'm not going to merge this pull request verbatim, but I've applied the spirit of what you meant, here…

https://github.com/nathansmith/javascript-quiz/commit/ec64cc9abd3281b3b7a78edee4a7a4e3989b0e70

**Comment by bfontaine** [comment]
This doesn’t work with large values, e.g.:

``` js
add( 1e306 ) === Infinity; // true

add( 1e300, 1e300) === 1e300 + 1e300; // false
```

**Comment by nathansmith** [comment]
Interesting. What would you suggest instead?

**Comment by bfontaine** [comment]
Using the `factor` trick only on the decimal part of each value, cf pull request #13.

**Pull request closed without merging**
